# Generated by Django 4.1.2 on 2022-10-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reading",
            old_name="cubic_meter",
            new_name="consumption",
        ),
    ]
