# Generated by Django 4.1.2 on 2022-10-21 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_cubic_meter_reading_consumption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectibles",
            name="amount",
            field=models.BigIntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name="collectibles",
            name="category",
            field=models.IntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name="collectibles",
            name="due_date",
            field=models.DateField(max_length=32),
        ),
        migrations.AlterField(
            model_name="collectibles",
            name="status",
            field=models.IntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name="reading",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
