# Generated by Django 4.1.2 on 2022-10-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_collectibles_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectibles",
            name="reading",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="base.reading",
            ),
        ),
        migrations.AlterField(
            model_name="collectibles",
            name="amount",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="collectibles",
            name="category",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="collectibles",
            name="status",
            field=models.IntegerField(),
        ),
    ]
