# Generated by Django 4.1.2 on 2022-10-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_collectibles_reading_alter_collectibles_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectibles",
            name="category",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="collectibles",
            name="status",
            field=models.CharField(max_length=32),
        ),
    ]
