# Generated by Django 4.1.2 on 2022-10-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_collectibles_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectibles",
            name="reading",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="base.reading",
            ),
        ),
    ]
