# Generated by Django 4.1.2 on 2022-10-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_collectibles_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="billing_month",
            field=models.DateField(blank=True, null=True),
        ),
    ]
