# Generated by Django 4.1.2 on 2022-10-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_reading_billing_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="multiplier",
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
