# Generated by Django 4.1.2 on 2022-10-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_reading_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectibles",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
